# Site settings
title: Sarath's blog
header-img: img/home-bg.jpg
email: apsarathchandar@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://sarathchandar.in/"
twitter_username: apsarathchandar
github_username:  apsarath
facebook_username:  sarath.chandar

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
gems: [jekyll-paginate]
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
